# Generated by Django 5.0.4 on 2024-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Complete',
            field=models.BooleanField(null=True),
        ),
    ]
