# Generated by Django 5.0.4 on 2024-05-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher')], max_length=20, null=True),
        ),
    ]
