# Generated by Django 5.0.4 on 2024-05-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='Type',
            new_name='Type_of_profile',
        ),
    ]
