# Generated by Django 5.0.4 on 2024-05-14 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_type_username_type_of_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='Password',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='username',
            name='Type_of_profile',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='username',
            name='User_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
