# Generated by Django 5.0.4 on 2024-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_task_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='Login',
            field=models.BooleanField(null=True),
        ),
    ]
