# Generated by Django 5.0.4 on 2024-05-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_username_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
