# Generated by Django 5.0.4 on 2024-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Piority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
    ]
