# Generated by Django 5.0.4 on 2024-05-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_task_piority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='About',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
