# Generated by Django 5.0.4 on 2024-05-15 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_username_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='Phone_number',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
