# Generated by Django 5.0.4 on 2024-05-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_username_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='About',
            field=models.TextField(),
        ),
    ]
