# Generated by Django 5.0.4 on 2024-05-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_task_description_alter_task_piority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='About',
            field=models.TextField(blank=True, null=True),
        ),
    ]
